language: android
env:
  global:
    - CODECOV_TOKEN="7a2f6b56-5f4d-41e7-816d-6f8e34c30d72"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-27
    - sys-img-armeabi-v7a-android-17
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - yes | sdkmanager "build-tools;28.0.2"

script: ./gradlew test build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
